"""Pydantic models for ParagonStats."""

from backend.models.images import (
    ImageConfig,
    ImageMetadata,
    ImageRequest,
    ImageResponse,
    ImageType,
)
from backend.models.receipt import (
    VAT_RATES,
    AddLineInput,
    BodyItemInput,
    DiscountLineInput,
    DiscountSummaryInput,
    DiscountVatInput,
    FileHashDB,
    FiscalFooterInput,
    HeaderDataInput,
    HeaderItemInput,
    HeaderTextInput,
    ImageInput,
    ItemDB,
    ItemResponse,
    PackDB,
    PackInput,
    PaymentInput,
    ReceiptDB,
    ReceiptInput,
    ReceiptResponse,
    SellLineInput,
    SumInCurrencyInput,
    UploadResult,
    VatRateSummaryInput,
    VatSummaryDB,
    VatSummaryInput,
    VoucherDB,
    clean_product_name,
    grosze_to_pln,
    parse_idz,
)
from backend.models.stats import (
    BasicStats,
    CategoryStats,
    DashboardStats,
    FunFact,
    MonthlySpending,
    StoreStats,
    TimeDistribution,
    TimeDistributionDay,
    TopProduct,
    WrappedData,
)
from backend.models.waitlist import (
    WaitlistDB,
    WaitlistEntry,
    WaitlistResponse,
    WaitlistStats,
)

__all__ = [
    # receipt.py - Helper functions
    "grosze_to_pln",
    "clean_product_name",
    "parse_idz",
    "VAT_RATES",
    # receipt.py - INPUT models
    "SellLineInput",
    "DiscountLineInput",
    "DiscountVatInput",
    "PackInput",
    "PaymentInput",
    "VatRateSummaryInput",
    "VatSummaryInput",
    "SumInCurrencyInput",
    "DiscountSummaryInput",
    "FiscalFooterInput",
    "HeaderDataInput",
    "HeaderTextInput",
    "AddLineInput",
    "ImageInput",
    "HeaderItemInput",
    "BodyItemInput",
    "ReceiptInput",
    # receipt.py - DB models
    "ReceiptDB",
    "ItemDB",
    "VoucherDB",
    "PackDB",
    "VatSummaryDB",
    "FileHashDB",
    # receipt.py - RESPONSE models
    "UploadResult",
    "ReceiptResponse",
    "ItemResponse",
    # stats.py
    "BasicStats",
    "TopProduct",
    "TimeDistributionDay",
    "TimeDistribution",
    "MonthlySpending",
    "StoreStats",
    "FunFact",
    "WrappedData",
    "CategoryStats",
    "DashboardStats",
    # waitlist.py
    "WaitlistEntry",
    "WaitlistDB",
    "WaitlistResponse",
    "WaitlistStats",
    # images.py
    "ImageType",
    "ImageRequest",
    "ImageConfig",
    "ImageResponse",
    "ImageMetadata",
]
